version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
  mongoDB:
    image: mongo
    ports:
      - "27017:27017"
    hostname: ${DB_HOST}

