version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
  mongoDB:
    image: mongo
    ports:
      - "${DB_PORT}:${DB_PORT}"
